handler: aime
dataset_path: AI-MO/aimo-validation-aime
dataset_split: train
question_key: problem
answer_key: answer
templating_parameters:
  template: "Please reason step by step, and put your final answer within \\boxed{{}}. {problem} <think>\n"
preprocess_config:
  url: "2023"
