handler: aime
dataset_path: yentinglin/aime_2025 # yentinglin/aime_2025
dataset_split: train
question_key: problem
answer_key: answer
templating_parameters:
  template: "Return your final response within \\boxed{{}}. {prompt}" # "{prompt}\nReturn your final response within \\boxed{{}}"

