handler: math
dataset_path: "qq8933/MATH500"  # repo ID in huggingface
dataset_subset: null # which subset on huggingface
question_key: problem
answer_key: answer
dataset_split: test
templating_parameters: 
  template: "Please reason step by step, and put your final answer within \\boxed{{}}. {problem} <think>\n"
# optional. Not supported yet. 
# fewshot_config:
#   - question: ...
#   - target:  ...
# num_fewshot: 0
